### ISSUE TITLE
The component stopped working

### ISSUE THREAD

**Issue by avbor** [Limych/ha-gismeteo#13]
**Versions**

* Version of the Home Assistant: 2021.2.3
* Version of the custom component: 2.0.22

**Configuration**
```yaml

- platform: gismeteo
  forecast: true
  monitored_conditions:
    - rain
    - snow
    - storm
    - geomagnetic

```

**Describe the bug**

Errors in HA log:
```
Logger: homeassistant.components.weather
Source: custom_components/gismeteo/__init__.py:336
Integration: Weather (documentation, issues)
First occurred: 15:24:20 (1 occurrences)
Last logged: 15:24:20

gismeteo: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 358, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gismeteo/weather.py", line 85, in update
    self._wd.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 285, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/gismeteo/__init__.py", line 336, in update
    xml = etree.fromstring(response)
  File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: mismatched tag: line 6, column 2
```

**To Reproduce**

Restart HA

**Expected behavior**
-

**Screenshots**

![image](https://user-images.githubusercontent.com/32452033/107849977-fb9f0680-6e0f-11eb-9028-d09ee2e17b4e.png)

**Comment by strannick-ru** [comment]
+1

**Comment by Repsionu** [comment]
+1
Something changed at provider side I guess...

**Comment by Limych** [comment]
It's was not a this component bug -- but Gismeteo bug. Invalid data response from server.
But now server send correct response.
