### ISSUE TITLE
Погода работает через раз, в логе сплошные ошибки

### ISSUE THREAD

**Issue by conrad66** [Limych/ha-gismeteo#14]
Home Assistant 2021.2.3
Компонент последней версии

2021-02-15 11:39:32 ERROR (MainThread) [homeassistant.helpers.entity] Update for weather.gismeteo fails
Traceback (most recent call last):
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/homeassistant/config/custom_components/gismeteo/weather.py", line 85, in update
    self._wd.update()
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/util/__init__.py", line 285, in wrapper
    result = method(*args, **kwargs)
  File "/opt/homeassistant/config/custom_components/gismeteo/__init__.py", line 336, in update
    xml = etree.fromstring(response)
  File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 1347, in XML
    parser.feed(text)
  File "<string>", line None

**Comment by Limych** [comment]
См. #13.
И, да, неиспользование предоставленного шаблона для багрепорта -- это достаточная причина для закрытия тикета даже без попытки в нём разобраться.
