### ISSUE TITLE
After update 2024.1.6 got error

### ISSUE THREAD

**Issue by VikeDragon** [Limych/ha-gismeteo#183]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

After update 2024.1.6 got error:
Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 10:36:28 (1 occurrences)
Last logged: 10:36:28

Error setting up entry configuration.yaml for gismeteo
Traceback (most recent call last):
  File "/config/custom_components/gismeteo/api.py", line 226, in async_get_location
    xml = etree.fromstring(response)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/xml/etree/ElementTree.py", line 1338, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: mismatched tag: line 6, column 2

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gismeteo/__init__.py", line 98, in async_setup_entry
    coordinator = await _async_get_coordinator(hass, uid, cfg)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gismeteo/__init__.py", line 77, in _async_get_coordinator
    await gismeteo.async_get_location()
  File "/config/custom_components/gismeteo/api.py", line 236, in async_get_location
    raise ApiError(
custom_components.gismeteo.api.ApiError: Can't retrieve location data! Invalid server response.

### Describe the solution you'd like

Get a working integration, such as updates.

### Describe alternatives you've considered

Get a working integration, such as updates.

### Additional context

Get a working integration, such as updates.

**Comment by VikeDragon** [comment]
It's very strange, after a day everything works fine
