### ISSUE TITLE
Gismeteo doesn't work on 2024.10.4

### ISSUE THREAD

**Issue by LeoeLeoeL** [Limych/ha-gismeteo#215]
### System Health details

![image](https://github.com/user-attachments/assets/b0f25f2d-d727-48b0-bc51-99f12f1c6559)
Unable to find the requested window.

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/Limych/ha-gismeteo/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

![image](https://github.com/user-attachments/assets/dbf4e058-c40a-4bea-864b-0a778dd86b06)

### Reproduction steps

1. Update HA from 2024.10.3 to 2024.10.4
2.
3.
...

### Debug logs

```text
Registratore: homeassistant.setup
Fonte: setup.py:334
Prima occorrenza: 14:31:42 (1 occorrenze)
Ultima registrazione: 14:31:42

Setup failed for custom integration 'gismeteo': Unable to import component: No module named 'aiofiles.threadpool.binary'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/gismeteo/__init__.py", line 39, in <module>
    from .api import ApiError, GismeteoApiClient
  File "/config/custom_components/gismeteo/api.py", line 57, in <module>
    from .cache import Cache
  File "/config/custom_components/gismeteo/cache.py", line 13, in <module>
    import aiofiles
  File "/usr/local/lib/python3.12/site-packages/aiofiles/__init__.py", line 2, in <module>
    from .threadpool import (
  File "/usr/local/lib/python3.12/site-packages/aiofiles/threadpool/__init__.py", line 15, in <module>
    from ..base import AiofilesContextManager
ModuleNotFoundError: No module named 'aiofiles.threadpool.binary'
```

**Comment by LeoeLeoeL** [comment]
I rebooted and now it works again
