### ISSUE TITLE
Can not install integration

### ISSUE THREAD

**Issue by bigbrother72** [Limych/ha-gismeteo#23]
Version of the Home Assistant:

Home Assistant 2021.2.3

Gismeteo ha-gismeteo 2.1.0

Dont install. Give error:

2021-03-02 14:14:19 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 136, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 69, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 130, in async_init
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 213, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/gismeteo/config_flow.py", line 95, in async_step_user
    default=self.hass.config.get(CONF_FORECAST, False),
AttributeError: 'Config' object has no attribute 'get'

**Comment by Limych** [comment]
Thank you.
But, please correct the bug report according to the provided template.

**Comment by shadowpanther** [comment]
Same error here.
Trying to add the integration via the Integrations list (as opposed to going through the config file).
Found Gismeteo, clicked. The message popped up "Error. Config flow could not be loaded".
In the log there is almost the same stacktrace as @bigbrother72 pasted. My copy follows:
```
home-assistant   | 2021-03-06 04:24:47 ERROR (MainThread) [aiohttp.server] Error handling request
home-assistant   | Traceback (most recent call last):
home-assistant   |   File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
home-assistant   |     resp = await self._request_handler(request)
home-assistant   |   File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
home-assistant   |     resp = await handler(request)
home-assistant   |   File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
home-assistant   |     return await handler(request)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
home-assistant   |     return await handler(request)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 172, in forwarded_middleware
home-assistant   |     return await handler(request)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
home-assistant   |     return await handler(request)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
home-assistant   |     return await handler(request)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 129, in auth_middleware
home-assistant   |     return await handler(request)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
home-assistant   |     result = await result
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 117, in post
home-assistant   |     return await super().post(request)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
home-assistant   |     result = await method(view, request, *args, **kwargs)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 69, in post
home-assistant   |     result = await self._flow_mgr.async_init(
home-assistant   |   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 133, in async_init
home-assistant   |     result = await self._async_handle_step(
home-assistant   |   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 216, in _async_handle_step
home-assistant   |     result: Dict = await getattr(flow, method)(user_input)
home-assistant   |   File "/config/custom_components/gismeteo/config_flow.py", line 93, in async_step_user
home-assistant   |     default=self.hass.config.get(CONF_FORECAST, False),
home-assistant   | AttributeError: 'Config' object has no attribute 'get'
```

Home Assistant 2021.3.1
ha-gismeteo 2.1.1

Adding through the config works fine.

**Comment by Masterz69** [comment]
Home Assistant OS 5.12, core-2021.3.0, HACS Gismeteo 2.1.1

Add-on installed Ok.
When try to add Integrations - "Config flow could not be loaded".

Core log - same as pasted @shadowpanther.

**Comment by barawkaa** [comment]
Dont work
`2021-03-13 09:18:00 ERROR (MainThread) [aiohttp.server] Error handling request


Traceback (most recent call last):


  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request


    resp = await self._request_handler(request)


  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle


    resp = await handler(request)


  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl


    return await handler(request)


  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware


    return await handler(request)


  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware


    return await handler(request)


  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware


    return await handler(request)


  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 129, in auth_middleware


    return await handler(request)


  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle


    result = await result


  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 117, in post


    return await super().post(request)


  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper


    result = await method(view, request, *args, **kwargs)


  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 69, in post


    result = await self._flow_mgr.async_init(


  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 133, in async_init


    result = await self._async_handle_step(


  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 216, in _async_handle_step


    result: Dict = await getattr(flow, method)(user_input)


  File "/config/custom_components/gismeteo/config_flow.py", line 93, in async_step_user


    default=self.hass.config.get(CONF_FORECAST, False),


AttributeError: 'Config' object has no attribute 'get'`
