### ISSUE TITLE
ImportError: cannot import name 'PERCENTAGE' from 'homeassistant.const'

### ISSUE THREAD

**Issue by turbulator** [Limych/ha-gismeteo#6]
В Homeassistant 0.115 отвалились homeassistant.const.PERCENTAGE, а вы их использовали с 2.0.18.
Очень много custom_components на этом полегло.

Поэтому теперь имеем:

```
Уровень: ERROR
Logger: homeassistant.config
Source: custom_components/gismeteo/const.py:16
First occurred: 8:14:36 (1 occurrences)
Last logged: 8:14:36

Platform error: weather
Traceback (most recent call last):
  File "/srv/homeassistant/lib64/python3.8/site-packages/homeassistant/config.py", line 804, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/srv/homeassistant/lib64/python3.8/site-packages/homeassistant/loader.py", line 389, in get_platform
    cache[full_name] = importlib.import_module(
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/gismeteo/__init__.py", line 37, in <module>
    from .const import (
  File "/home/homeassistant/.homeassistant/custom_components/gismeteo/const.py", line 16, in <module>
    from homeassistant.const import (
ImportError: cannot import name 'PERCENTAGE' from 'homeassistant.const' (/srv/homeassistant/lib64/python3.8/site-packages/homeassistant/const.py)

```

**Comment by Limych** [comment]
Вы ошибаетесь. Полегли другие компоненты на импорте UNIT_PERCENTAGE, а не на PERCENTAGE.

Впрочем, для таких случаев, как у Вас, когда используется уже устаревшая версия HA, я сделал исправление в коде. См. свежую версию 2.0.20

**Comment by turbulator** [comment]
Действительно, на 0.115.6 компонент 2.0.18 прекрасно работает. Спасибо!
